### Get Token
POST http://localhost:8081/auth
Content-Type: application/json

{
  "email": "od3",
  "password": "1234"
}

> {%
  client.global.set("Authorization", response.body.data.accessToken);
%}

### Register Product
POST http://localhost:8082/products
Content-Type: application/json
Authorization: {{Authorization}}

{
  "productName": "아이다스 바람막이 컬렉션 할인",
  "category": "FASHION",
  "price": 10000,
  "quantity": 30,
  "productImgUrl": "imgUrl",
  "descriptionImgUrl": "descriptionImgUrl",
  "productOption": [
    "100",
    "120"
  ]
}
